//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "carts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: String,
    pub product_id: Uuid,
    pub total_qty: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}


#[derive(Deserialize)]
pub struct NewCart {
    pub user_id: Uuid,
    pub product_id: Uuid,
    pub total_qty: i32,
}

#[derive(Debug, Serialize, Deserialize, FromQueryResult)]
pub struct CartsResponse {
    pub id: Uuid,
    pub product_id: Uuid,
    pub total_qty: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub product_name: String,
    pub description: String,
    pub product_price: BigDecimal,
    pub sub_total_price: BigDecimal,
    pub img_url: String,
}